name: PR Check for packages/api

on:
  pull_request:
    paths:
      - 'packages/api/**'
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install -DskipTests
        working-directory: packages/api

      - name: Run Spotless Check
        run: mvn spotless:check
        working-directory: packages/api
